config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'appointments#quote'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Ruta nesteado con only vacío
  # para evitar duplicación de routes
  resources :users, only: [] do
    resources :appointments, only: %i[index new create edit update destroy]
    get 'quote', to: "appointments#quote"
  end

  resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  # Asociaciones
  belongs_to :user
  belongs_to :patient

  # Validaciones
  validates :date, :patient_id, presence: true
  validates :time, uniqueness: { scope: [:date, :user_id]}

  def cita
    self.date.strftime("%a, %e %b %Y")
  end

end

app/models/patient.rb
class Patient < ApplicationRecord

  # Asociaciones
  has_many :users, through: :appointments
  has_many :appointments, dependent: :destroy

  # Validaciones
  validates :name, :last_name, :phone, presence: true

  def complete_name
    self.name + " " + self.last_name
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Asociaciones
  has_many :patients, through: :appointments
  has_many :appointments, dependent: :destroy


  # Validaciones
  validates :name, :last_name, :phone, :email, presence: true
  validates :phone, length: {minimum: 9}
  validates :email, presence: true, format: { with: /\A[\w|.|-]+@[\w|-]+\.\w+\z/ }

  def complete_name
    self.name + " " + self.last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name, :phone, :specialty])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name, :phone, :specialty])
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  before_action :set_appointment, only: [ :show, :edit, :update, :destroy]
  before_action :set_user, only: [:new, :create]

  def quote
    @appointments = Appointment.where(date: Date.today)
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointments_params)
    @appointment.user_id = current_user.id
    if @appointment.save
      redirect_to root_path
      flash[:alert] = "Se agendó su cita correctamente"
    else
      flash[:alert] = "Hubo un error al agendar su cita"
      render :new
    end
  end


  def edit
  end

  def update
    @appointment = @appointment.user_id.find(params[:id])
    @appointment.update(appointments_params)
    @appointments = current_user.appointment

    if @appointments.save
      redirect_to appoinments_path
      flash[:notice] = "La cita se actualizó correctamente"
    end
  end

  def destroy
    @appointment.destroy
  end


  private

  def set_user
    @user = current_user
  end

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointments_params
    params.require(:appointment).permit(:date, :time, :user_id, :patient_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  # before_action :patient_params , only: [:create, :update]

  def index
    @patients = Patient.all
  end

  def show
    # patient seteado en el before_action
  end
  
  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.complete_name.capitalize
    if @patient.save
      redirect_to root_path
    else
      flash[:alert] = "El paciente no se creó correctamente"
      render :new
    end
  end

  def edit
    # patient seteado en el before_action
  end

  def update
    @patient.update(patient_params)
    redirect_to patients_path
    flash[:alert] = "El paciente se actualizó correctamente"
  end

  def destroy
    @patient.destroy
      redirect_to root_path
      flash[:notice] = "El paciente se eliminó correctamente"
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :last_name, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_form.html.erb
<div class="container">

  <div class="patient-form">
    <%= simple_form_for ([@user, @appointment]) do |f| %>
      <%= f.input :date, label: "Asignar día de consulta" %>
      <%= f.input :time, label: "Asignar hora de consulta" %>
      <%= f.association :patient, collection: Patient.order(:name), label: "Paciente" %>
      <%= f.button :submit, "Crear cita médica", class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="container">
<h1 class= "text-center mt-3">Agendar Cita Médica</h1>

<%= render 'form', appointment: @appointment %>
</div>

app/views/appointments/quote.html.erb
  <h1 class= "text-center mt-3">Citas Médicas</h1>

  <%= @appointments.each do |f| %>
<div class="container">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"> Dr(a) <%= f.user.name + " " + f.user.last_name%></h5>
      <h6 class="card-subtitle mb-2 text-muted">    <%= f.patient.complete_name.capitalize %></h6>
      <p class="card-text"> <%= f.date %>
        <%= f.time.strftime("%H:%M") %>
      </p>
    </div>
  </div>
</div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProyect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Test</h1>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <%= link_to  "Nuevo paciente", new_patient_path %>
       <%# <%= link_to  "Nueva cita médica", new_user_appointment_path%> %>

app/views/patients/_form.html.erb
<div class="container">
  <h1 class= "text-center mt-5">Creando Paciente</h1>

  <div class="patient-form">
    <%= simple_form_for @patient do |f| %>
      <%= f.input :name, label: "Nombre" %>
      <%= f.input :last_name, label: "Apellido" %>
      <%= f.input :phone, label: "Teléfono"  %>
      <%= f.button :submit, "Crear paciente", class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/patients/new.html.erb
<%= render 'form', patient: @patient %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Agendar cita", new_user_appointment_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Pacientes", new_patient_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/pabloems", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>